/**
 * plan.mjs — compute the timeline plan from measured VO clip durations.
 *
 * Reads the six vo-*.mp3 durations, assigns each video segment a duration
 * aligned to its VO line(s) plus a breath pad, then emits:
 *   - output/plan.json     (segment list with durations)
 *   - output/captions.srt  (timed to the assembled timeline)
 *
 * The total lands inside 88–92s by construction; if VO is short, the outro
 * hold absorbs the slack (and is clamped so the outro never drops below 6s).
 *
 * Usage: node scripts/video/lib/plan.mjs
 */

import { execFileSync } from 'node:child_process';
import { writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const SHOTS = resolve(ROOT, 'output/shots');
const OUT = resolve(ROOT, 'output');
const FFPROBE = process.env.FFPROBE || '/opt/homebrew/bin/ffprobe';

function dur(file) {
  if (!existsSync(file)) return 0;
  try {
    const out = execFileSync(
      FFPROBE,
      ['-v', 'error', '-show_entries', 'format=duration', '-of', 'csv=p=0', file],
      { encoding: 'utf8' },
    );
    const n = parseFloat(out.trim());
    return Number.isFinite(n) ? n : 0;
  } catch {
    return 0;
  }
}

const GAP = 0.35; // breath gap inserted between VO lines
const round2 = (n) => Math.round(n * 100) / 100;

// VO clip durations (seconds).
const vo = {
  v1: dur(resolve(SHOTS, 'vo-1.mp3')),
  v2a: dur(resolve(SHOTS, 'vo-2a.mp3')),
  v2b: dur(resolve(SHOTS, 'vo-2b.mp3')),
  v2c: dur(resolve(SHOTS, 'vo-2c.mp3')),
  v3: dur(resolve(SHOTS, 'vo-3.mp3')),
  vo_: dur(resolve(SHOTS, 'vo-outro.mp3')),
};

// ── Map each visual segment to a duration driven by its VO line(s). ──
// type: 'canvas' shots are generated by ffmpeg; 'video' shots come from
// Playwright WebM (with a canvas fallback if the capture is missing).
const PAD_VIDEO = 1.6; // hold past the VO so motion breathes
const segments = [
  { id: 'type1', type: 'canvas', voStart: 0, seconds: 0 },           // first half of vo-1
  { id: 'type2', type: 'canvas', voStart: 0, seconds: 0 },           // second half of vo-1
  { id: 'live-bloom', type: 'video', src: 'live-bloom.webm', seconds: round2(vo.v2a + PAD_VIDEO) },
  { id: 'live-teams', type: 'video', src: 'live-teams.webm', seconds: round2(vo.v2b + PAD_VIDEO) },
  { id: 'onboarding-voice', type: 'video', src: 'onboarding-voice.webm', seconds: round2(vo.v2c + PAD_VIDEO) },
  { id: 'customers-hero', type: 'video', src: 'customers-hero.webm', seconds: round2(vo.v3 * 0.45 + 0.8) },
  { id: 'customers-story', type: 'video', src: 'customers-story.webm', seconds: round2(vo.v3 * 0.55 + 0.8) },
  { id: 'numbers', type: 'canvas', seconds: 4.2 },
  { id: 'outro', type: 'canvas', seconds: 0 },
];

// Split vo-1 across the two type cards.
const t1 = round2(vo.v1 * 0.45 + 0.4);
const t2 = round2(vo.v1 * 0.55 + 0.8);
segments[0].seconds = t1;
segments[1].seconds = t2;

// Outro hold: VO-outro + 6s minimum hold, clamped so total stays <= 92.
const provisionalTotal = segments
  .filter((s) => s.id !== 'outro')
  .reduce((a, s) => a + s.seconds, 0);
let outroHold = round2(Math.max(vo.vo_ + 6.0, 7.5));
let total = provisionalTotal + outroHold;
if (total > 92) {
  outroHold = round2(Math.max(6.0, outroHold - (total - 91)));
  total = provisionalTotal + outroHold;
}
// If we somehow fall under 88, lengthen the outro hold.
if (total < 88) {
  outroHold = round2(outroHold + (88.5 - total));
  total = provisionalTotal + outroHold;
}
segments[segments.length - 1].seconds = outroHold;

// ── Build SRT (timed to assembled timeline). ──
// VO is laid down sequentially with GAP between lines, starting at t=0.
function srtTime(s) {
  const ms = Math.round(s * 1000);
  const h = String(Math.floor(ms / 3600000)).padStart(2, '0');
  const m = String(Math.floor((ms % 3600000) / 60000)).padStart(2, '0');
  const sec = String(Math.floor((ms % 60000) / 1000)).padStart(2, '0');
  const mil = String(ms % 1000).padStart(3, '0');
  return `${h}:${m}:${sec},${mil}`;
}

const captionLines = [
  { d: vo.v1, text: ['Every important conversation', "happens once. You don't get to rehearse."] },
  { d: vo.v2a, text: ['Vought listens to your live conversation —', 'separating every speaker, understanding the moment,', 'whispering the next line into your ear.'] },
  { d: vo.v2b, text: ['In under four hundred milliseconds.', 'Built on the ElevenLabs Speech Engine.'] },
  { d: vo.v2c, text: ['Thirty seconds of recording.', 'The voice you hear in your ear is yours.'] },
  { d: vo.v3, text: ['TripleByte closed $1.4M more last quarter.', 'Suggestion acceptance tripled.', 'The conversation goes the way it was always supposed to.'] },
  { d: vo.vo_, text: ['Vought. Intelligence for live conversations.'] },
];

let cursor = 0.2; // small lead-in
let srt = '';
let idx = 1;
const voSequence = [];
for (const line of captionLines) {
  const start = cursor;
  const end = round2(cursor + line.d);
  voSequence.push({ start: round2(start), dur: line.d });
  srt += `${idx}\n${srtTime(start)} --> ${srtTime(end)}\n${line.text.join('\n')}\n\n`;
  cursor = round2(end + GAP);
  idx += 1;
}

writeFileSync(resolve(OUT, 'captions.srt'), srt, 'utf8');
writeFileSync(
  resolve(ROOT, 'captions.srt'),
  srt,
  'utf8',
); // also keep a copy alongside the scripts (deliverable path)

const plan = {
  fps: 30,
  width: 1920,
  height: 1080,
  total: round2(total),
  voTotalSpoken: round2(cursor - GAP),
  segments: segments.map((s) => ({ ...s, seconds: round2(s.seconds) })),
  voSequence,
};
writeFileSync(resolve(OUT, 'plan.json'), JSON.stringify(plan, null, 2), 'utf8');

console.log('VO durations (s):', Object.fromEntries(Object.entries(vo).map(([k, v]) => [k, round2(v)])));
console.log('Segment durations (s):');
for (const s of plan.segments) console.log(`  ${s.id.padEnd(18)} ${s.seconds}`);
console.log('Assembled total (s):', plan.total, '| outro hold:', outroHold);
if (plan.total < 88 || plan.total > 92) {
  console.error(`WARNING: total ${plan.total}s is outside 88–92s window`);
}
